### ISSUE TITLE
Server crashed when trying to crete a project

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#10698]
### Description

> {"level":"warn","message":"Error parsing dbt json log Unexpected token 'U', \"Unsupporte\"... is not valid JSON","stack":"SyntaxError: Unexpected token 'U', \"Unsupporte\"... is not valid JSON\n    at JSON.parse (<anonymous>)\n    at /usr/app/packages/backend/dist/dbt/dbtCliClient.js:100:34\n    at Array.reduce (<anonymous>)\n    at DbtCliClient.parseDbtJsonLogs (/usr/app/packages/backend/dist/dbt/dbtCliClient.js:98:30)\n    at DbtCliClient.<anonymous> (/usr/app/packages/backend/dist/dbt/dbtCliClient.js:154:37)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/app/packages/backend/dist/dbt/dbtCliClient.js:28:58)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-07-11 14:29:45"}

Thread: https://lightdash.slack.com/archives/C06PAQCH932/p1720631317725549

### Steps to Reproduce the Bug or Issue

tbd

### Cloud or self-hosting

None

**Comment by rephus** [comment]
Suggestion, at the time of this error, check the real memory on the GCP monitoring to confirm this is a OOM error caused by the project. JS might be limited to 1.5gb anyway
