### ISSUE TITLE
Error on lightdash start-preview: ReferenceError: crypto is not defined

### ISSUE THREAD

**Issue by jpetey75** [lightdash/lightdash#11797]
### Description

There have been two reports of this error from customers when running `lightdash start-preview`:

```
Compiled 247 explores, SUCCESS=247 ERRORS=0
Project updated on ***/projects/c29d7b34-95a6-496c-b073-576e996090de/tables
crypto is not defined
ReferenceError: crypto is not defined
    at prepareKeyValueMessage (/usr/local/lib/node_modules/@lightdash/cli/node_modules/@actions/core/lib/file-command.js:47:39)
    at Object.setOutput (/usr/local/lib/node_modules/@lightdash/cli/node_modules/@actions/core/lib/core.js:168:105)
    at /usr/local/lib/node_modules/@lightdash/cli/dist/handlers/preview.js:409:26
    at step (/usr/local/lib/node_modules/@lightdash/cli/dist/handlers/preview.js:67:23)
    at Object.next (/usr/local/lib/node_modules/@lightdash/cli/dist/handlers/preview.js:48:53)
    at fulfilled (/usr/local/lib/node_modules/@lightdash/cli/dist/handlers/preview.js:39:58)
ReferenceError: crypto is not defined
    at prepareKeyValueMessage (/usr/local/lib/node_modules/@lightdash/cli/node_modules/@actions/core/lib/file-command.js:47:39)
    at Object.setOutput (/usr/local/lib/node_modules/@lightdash/cli/node_modules/@actions/core/lib/core.js:168:105)
    at /usr/local/lib/node_modules/@lightdash/cli/dist/handlers/preview.js:409:26
    at step (/usr/local/lib/node_modules/@lightdash/cli/dist/handlers/preview.js:67:23)
    at Object.next (/usr/local/lib/node_modules/@lightdash/cli/dist/handlers/preview.js:48:53)
    at fulfilled (/usr/local/lib/node_modules/@lightdash/cli/dist/handlers/preview.js:39:58)
```

### Steps to Reproduce the Bug or Issue

Still investigating a way to reproduce - the command works okay locally from what we can tell, but fails in GH actions, here are the commands customers used to hit the error:

```
lightdash start-preview --project-dir . --profiles-dir . --name $***GITHUB_HEAD_REF##*/***
```

```
lightdash start-preview --name "some name" --exclude "tag:some_tag"
```

### version

cli@0.1293.0

### Cloud or self-hosting

cloud

**Comment by jpetey75** [comment]
We are also seeing this error on our internal project: https://github.com/lightdash/lightdash-analytics/actions/runs/11177721070/job/31073782631?pr=530

**Comment by IrakliJani** [comment]
more context: https://github.com/actions/toolkit/issues/1841
