### ISSUE TITLE
Cannot read properties of undefined (reading 'charAt')

### ISSUE THREAD

**Issue by charlespicowski** [lightdash/lightdash#3131]
Looks like a typo?

### Description

Running `lightdash generate -s fct_dbt_node_cost` produces

```✖   Failed to generate fct_dbt_node_cost.yml
Cannot read properties of undefined (reading 'charAt')
TypeError: Cannot read properties of undefined (reading 'charAt')
    at next (/usr/local/lib/node_modules/@lightdash/cli/node_modules/@humanwhocodes/momoa/api.js:235:22)
    at tokenize (/usr/local/lib/node_modules/@lightdash/cli/node_modules/@humanwhocodes/momoa/api.js:491:13)
    at parse (/usr/local/lib/node_modules/@lightdash/cli/node_modules/@humanwhocodes/momoa/api.js:726:20)
    at Object.src_default (/usr/local/lib/node_modules/@lightdash/cli/node_modules/better-ajv-errors/lib/cjs/index.js:31:42)
    at /usr/local/lib/node_modules/@lightdash/cli/dist/dbt/schema.js:51:51
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/@lightdash/cli/dist/dbt/schema.js:24:58)
TypeError: Cannot read properties of undefined (reading 'charAt')
    at next (/usr/local/lib/node_modules/@lightdash/cli/node_modules/@humanwhocodes/momoa/api.js:235:22)
    at tokenize (/usr/local/lib/node_modules/@lightdash/cli/node_modules/@humanwhocodes/momoa/api.js:491:13)
    at parse (/usr/local/lib/node_modules/@lightdash/cli/node_modules/@humanwhocodes/momoa/api.js:726:20)
    at Object.src_default (/usr/local/lib/node_modules/@lightdash/cli/node_modules/better-ajv-errors/lib/cjs/index.js:31:42)
    at /usr/local/lib/node_modules/@lightdash/cli/dist/dbt/schema.js:51:51
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/@lightdash/cli/dist/dbt/schema.js:24:58)
```

### To Reproduce

Not sure how I did this. I had Lightdash preview running at the same time as trying to generate new yaml, maybe this is why.

### App Version

```0.228.0```

**Comment by ZeRego** [comment]
@charlespicowski I was only able to replicate this issue when the model yml was completely empty. Is this the case for `fct_dbt_node_cost` ?

**Comment by ZeRego** [comment]
Related to https://github.com/atlassian/better-ajv-errors/issues/154
