### ISSUE TITLE
fast install fails due to missing LIGHTDASH_QUERY_MAX_LIMIT in env file 

### ISSUE THREAD

**Issue by olly-writes-code** [lightdash/lightdash#3577]
### Description
Local fast install fails. 

Stacktrace
```
docker-compose logs
Attaching to lightdash_lightdash_1, lightdash_db_1
db_1         | The files belonging to this database system will be owned by user "postgres".
db_1         | This user must also own the server process.
db_1         |
db_1         | The database cluster will be initialized with locale "en_US.utf8".
db_1         | The default database encoding has accordingly been set to "UTF8".
db_1         | The default text search configuration will be set to "english".
db_1         |
db_1         | Data page checksums are disabled.
db_1         |
db_1         | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db_1         | creating subdirectories ... ok
db_1         | selecting dynamic shared memory implementation ... posix
db_1         | selecting default max_connections ... 100
db_1         | selecting default shared_buffers ... 128MB
db_1         | selecting default time zone ... Etc/UTC
db_1         | creating configuration files ... ok
db_1         | running bootstrap script ... ok
db_1         | performing post-bootstrap initialization ... ok
db_1         | syncing data to disk ... ok
db_1         |
db_1         |
db_1         | Success. You can now start the database server using:
db_1         |
db_1         |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db_1         |
db_1         | initdb: warning: enabling "trust" authentication for local connections
db_1         | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
db_1         | waiting for server to start....2022-10-25 14:00:26.540 UTC [48] LOG:  starting PostgreSQL 15.0 (Debian 15.0-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
db_1         | 2022-10-25 14:00:26.543 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1         | 2022-10-25 14:00:26.552 UTC [51] LOG:  database system was shut down at 2022-10-25 14:00:26 UTC
db_1         | 2022-10-25 14:00:26.557 UTC [48] LOG:  database system is ready to accept connections
db_1         |  done
db_1         | server started
db_1         |
db_1         | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
db_1         |
db_1         | 2022-10-25 14:00:26.734 UTC [48] LOG:  received fast shutdown request
db_1         | waiting for server to shut down....2022-10-25 14:00:26.738 UTC [48] LOG:  aborting any active transactions
db_1         | 2022-10-25 14:00:26.739 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
db_1         | 2022-10-25 14:00:26.739 UTC [49] LOG:  shutting down
db_1         | 2022-10-25 14:00:26.741 UTC [49] LOG:  checkpoint starting: shutdown immediate
db_1         | 2022-10-25 14:00:26.754 UTC [49] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.005 s, sync=0.002 s, total=0.016 s; sync files=2, longest=0.001 s, average=0.001 s; distance=0 kB, estimate=0 kB
db_1         | 2022-10-25 14:00:26.757 UTC [48] LOG:  database system is shut down
db_1         |  done
db_1         | server stopped
db_1         |
db_1         | PostgreSQL init process complete; ready for start up.
db_1         |
db_1         | 2022-10-25 14:00:26.857 UTC [1] LOG:  starting PostgreSQL 15.0 (Debian 15.0-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
db_1         | 2022-10-25 14:00:26.859 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1         | 2022-10-25 14:00:26.859 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1         | 2022-10-25 14:00:26.865 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1         | 2022-10-25 14:00:26.871 UTC [61] LOG:  database system was shut down at 2022-10-25 14:00:26 UTC
db_1         | 2022-10-25 14:00:26.876 UTC [1] LOG:  database system is ready to accept connections
db_1         | 2022-10-25 14:05:26.971 UTC [59] LOG:  checkpoint starting: time
db_1         | 2022-10-25 14:05:30.994 UTC [59] LOG:  checkpoint complete: wrote 43 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=4.011 s, sync=0.004 s, total=4.024 s; sync files=11, longest=0.003 s, average=0.001 s; distance=252 kB, estimate=252 kB
lightdash_1  | yarn workspace v1.22.19
lightdash_1  | yarn run v1.22.19
lightdash_1  | $ knex migrate:latest --knexfile dist/database/knexfile.js
lightdash_1  | Working directory changed to /usr/app/packages/backend/dist/database
lightdash_1  | 2022-10-25 14:47:00 [Lightdash] warn: Using http://localhost:8080 as the base SITE_URL for Lightdash. This is not suitable for production. Update with a top level domain using https such as https://lightdash.mycompany.com
lightdash_1  | Cannot parse environment variable "LIGHTDASH_QUERY_MAX_LIMIT". Value must be an integer but LIGHTDASH_QUERY_MAX_LIMIT=
lightdash_1  | ParseError: Cannot parse environment variable "LIGHTDASH_QUERY_MAX_LIMIT". Value must be an integer but LIGHTDASH_QUERY_MAX_LIMIT=
lightdash_1  |     at getIntegerFromEnvironmentVariable (/usr/app/packages/backend/dist/config/parseConfig.js:20:15)
lightdash_1  |     at mergeWithEnvironment (/usr/app/packages/backend/dist/config/parseConfig.js:92:69)
lightdash_1  |     at parseConfig (/usr/app/packages/backend/dist/config/parseConfig.js:111:12)
lightdash_1  |     at Object.<anonymous> (/usr/app/packages/backend/dist/config/lightdashConfig.js:46:57)
lightdash_1  |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
lightdash_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
lightdash_1  |     at Module.load (internal/modules/cjs/loader.js:950:32)
lightdash_1  |     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
lightdash_1  |     at Module.require (internal/modules/cjs/loader.js:974:19)
lightdash_1  |     at require (internal/modules/cjs/helpers.js:101:18)
lightdash_1  | error Command failed with exit code 1.
lightdash_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lightdash_1  | error Command failed.
lightdash_1  | Exit code: 1
lightdash_1  | Command: /usr/local/bin/node
lightdash_1  | Arguments: /opt/yarn-v1.22.19/lib/cli.js migrate-production
lightdash_1  | Directory: /usr/app/packages/backend
lightdash_1  | Output:
lightdash_1  |
lightdash_1  | info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
```

Fixed by (via slack [support](https://lightdash-community.slack.com/archives/C03MG2VTR08/p1666710593168889?thread_ts=1666709369.322809&cid=C03MG2VTR08)) :

Edit the file `.env.fast-install` and add, at the end:
`LIGHTDASH_QUERY_MAX_LIMIT=5000`
And then try again the install script.

### To Reproduce
Run `scripts/install.sh`

### App Version

0.298.1

**Comment by ZeRego** [comment]
@all-contributors add @olly-writes-code for bugs
