### ISSUE TITLE
Scheduled delivery for images should only be available when headless browser is configured

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#4587]
### Description

Error when a scheduled delivery tried to generate an image when there is no headless browser configured:

```
2023-02-23T17:38:04.032861+00:00 app[web.1]:   TypeError: Only absolute URLs are supported
2023-02-23T17:38:04.032862+00:00 app[web.1]:       at getNodeRequestOptions (/usr/app/node_modules/node-fetch/lib/index.js:1327:9)
2023-02-23T17:38:04.032862+00:00 app[web.1]:       at /usr/app/node_modules/node-fetch/lib/index.js:1440:19
2023-02-23T17:38:04.032863+00:00 app[web.1]:       at new Promise (<anonymous>)
2023-02-23T17:38:04.032863+00:00 app[web.1]:       at fetch (/usr/app/node_modules/node-fetch/lib/index.js:1437:9)
2023-02-23T17:38:04.032864+00:00 app[web.1]:       at UnfurlService.<anonymous> (/usr/app/packages/backend/dist/services/UnfurlService/UnfurlService.js:237:61)
2023-02-23T17:38:04.032864+00:00 app[web.1]:       at Generator.next (<anonymous>)
2023-02-23T17:38:04.032864+00:00 app[web.1]:       at /usr/app/packages/backend/dist/services/UnfurlService/UnfurlService.js:31:71
2023-02-23T17:38:04.032864+00:00 app[web.1]:       at new Promise (<anonymous>)
2023-02-23T17:38:04.032865+00:00 app[web.1]:       at __awaiter (/usr/app/packages/backend/dist/services/UnfurlService/UnfurlService.js:27:12)
2023-02-23T17:38:04.032865+00:00 app[web.1]:       at UnfurlService.getUserCookie (/usr/app/packages/backend/dist/services/UnfurlService/UnfurlService.js:235:16)
2023-02-23T17:38:04.032865+00:00 app[web.1]:       at UnfurlService.<anonymous> (/usr/app/packages/backend/dist/services/UnfurlService/UnfurlService.js:274:39)
2023-02-23T17:38:04.032865+00:00 app[web.1]:       at Generator.next (<anonymous>)
2023-02-23T17:38:04.032866+00:00 app[web.1]:       at /usr/app/packages/backend/dist/services/UnfurlService/UnfurlService.js:31:71
2023-02-23T17:38:04.032866+00:00 app[web.1]:       at new Promise (<anonymous>)
2023-02-23T17:38:04.032866+00:00 app[web.1]:       at __awaiter (/usr/app/packages/backend/dist/services/UnfurlService/UnfurlService.js:27:12)
2023-02-23T17:38:04.032866+00:00 app[web.1]:       at UnfurlService.unfurlImage (/usr/app/packages/backend/dist/services/UnfurlService/UnfurlService.js:273:16)
2023-02-23T17:38:12.053055+00:00 app[web.1]: 2023-02-23 17:38:12 [Lightdash] [32minfo[39m: [32mProcessing new job sendEmailNotification[39m
2023-02-23T17:38:12.060660+00:00 app[web.1]: 2023-02-23 17:38:12 [Lightdash] [31merror[39m: [31mUnable to send notification on email : {}[39m
2023-02-23T17:38:12.061557+00:00 app[web.1]: [worker(worker-913cbeef55c4970584)] ERROR: Failed task 803 (sendEmailNotification) with error Only absolute URLs are supported (8.64ms):
```

We should not have the image option if the headless browser is not available. Or another approach to avoid this error.

### App Version

0.430.0

**Comment by rephus** [comment]
Normally when headless browser is not defined, we get this error 
```
2023-02-24 08:57:54 [Lightdash] error: Unable to fetch screenshots from headless chrome Invalid URL: ws://undefined:undefined
```

I think this is something else
