### ISSUE TITLE
Unexpected token '.' when installing Lightdash CLI on a new codespaces instance

### ISSUE THREAD

**Issue by deepskydata** [lightdash/lightdash#5038]
### Description

In a new Github codespaces instance when run "lightdash"  get this error:

`
/usr/local/lib/node_modules/@lightdash/cli/node_modules/liquidjs/dist/liquid.node.cjs.js:1971
            : (isFunction(options?.handler) ? options.handler : identify);
                                  ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@lightdash/cli/node_modules/@lightdash/common/dist/templating/template.js:4:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
`

### To Reproduce
1. Set up a new codespace
2. Install NodeJS & npm
sudo apt install nodejs npm

3. Install lightdash
npm install -g @lightdash/cli
Does result in this error:
`
npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules'
npm ERR! }
`
sudo npm install -g @lightdash/cli
Does work
### App Version
No version defined

**Comment by deepskydata** [comment]
Ok. I Solved it.

In the end, it was what you already described in the docs:
"If you get an npm ERR! code EACCES error while installing the Lightdash CLI, [follow this guide](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally) to resolve it."

In the end, this was the way - install nvm, then use it to install node.

Interestingly - I never needed that before in a codespace setup. But there might be a change in the base image.
