### ISSUE TITLE
Error when sending CSV scheduled deliveries 

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#5059]
### Description

```
2023-04-12 06:56:32 [Lightdash] error: Failed task 470 (handleScheduledDelivery) with error Cannot convert undefined or null to object (3241.93ms):
  TypeError: Cannot convert undefined or null to object
      at Function.keys (<anonymous>)
      at Function.<anonymous> (/usr/app/packages/backend/dist/services/CsvService/CsvService.js:124:43)
      at Generator.next (<anonymous>)
      at /usr/app/packages/backend/dist/services/CsvService/CsvService.js:31:71
      at new Promise (<anonymous>)
      at __awaiter (/usr/app/packages/backend/dist/services/CsvService/CsvService.js:27:12)
      at Function.writeRowsToFile (/usr/app/packages/backend/dist/services/CsvService/CsvService.js:114:16)
      at CsvService.<anonymous> (/usr/app/packages/backend/dist/services/CsvService/CsvService.js:214:45)
      at Generator.next (<anonymous>)
      at fulfilled (/usr/app/packages/backend/dist/services/CsvService/CsvService.js:28:58)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

tested on eu1.lightdash.cloud

for a dashboard on email 

![image](https://user-images.githubusercontent.com/1983672/231376707-2b2ef456-7ff0-4dbe-b2c5-404230b49cf6.png)

**Comment by rephus** [comment]
I tseems this is happening when a chart on a dashboard has no results
