### ISSUE TITLE
Invalid URL - self hosted lightdash on Kubernetes

### ISSUE THREAD

**Issue by rauerhans** [lightdash/lightdash#5195]
### Description

Followed instructions to set up my dbt project on a self hosted lightdash and got an error during CLI login process.

### To Reproduce

Instructions given:
```console
#1 install lightdash CLI
npm install -g @lightdash/cli@0.370.0

#2 login to lightdash
lightdash login lightdash.luegnix.yadayada.app

#3 create project
lightdash deploy --create
```

Got this error at step 2:
```console
❯ lightdash login lightdash.luegnix.yadayada.app
(node:49241) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
? email: ************
? password: [hidden]
Invalid URL
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:387:5)
    at URL.onParseError (node:internal/url:565:9)
    at new URL (node:internal/url:641:5)
    at new URL (node:internal/url:638:22)
    at /usr/local/lib/node_modules/@lightdash/cli/dist/handlers/login.js:137:28
    at step (/usr/local/lib/node_modules/@lightdash/cli/dist/handlers/login.js:67:23)
    at Object.next (/usr/local/lib/node_modules/@lightdash/cli/dist/handlers/login.js:48:53)
    at fulfilled (/usr/local/lib/node_modules/@lightdash/cli/dist/handlers/login.js:39:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  input: 'lightdash.luegnix.yadayada.app',
  code: 'ERR_INVALID_URL'
}
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:387:5)
    at URL.onParseError (node:internal/url:565:9)
    at new URL (node:internal/url:641:5)
    at new URL (node:internal/url:638:22)
    at /usr/local/lib/node_modules/@lightdash/cli/dist/handlers/login.js:137:28
    at step (/usr/local/lib/node_modules/@lightdash/cli/dist/handlers/login.js:67:23)
    at Object.next (/usr/local/lib/node_modules/@lightdash/cli/dist/handlers/login.js:48:53)
    at fulfilled (/usr/local/lib/node_modules/@lightdash/cli/dist/handlers/login.js:39:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

The API appears to not like the URL.
Perhaps the URL is too long, too many subdomains? Pretty sure we have set it up nicely on Kubernetes, should not be an issue with our setup.

### App Version
Version: v0.370.0

**Comment by elton-okawa** [comment]
Hi @rauerhans, it seems an error with given url by looking at those lines:
```
TypeError [ERR_INVALID_URL]: Invalid URL
...
at new URL (node:internal/url:641:5)
```

It seems that built in Node.js `URL` requires `https://` or `http://` (depending on if you are using TLS or not), could you try adding it?
```
lightdash login https://lightdash.luegnix.yadayada.app
```
