### ISSUE TITLE
Stop subsequent Scheduled Delivery jobs after deletion

### ISSUE THREAD

**Issue by joaoviana** [lightdash/lightdash#5298]
### Description

Currently, if users delete a Scheduled Delivery, the jobs will try to keep running in the Worker even though the `Scheduler not found`. 
Example: 
```shell
2023-05-02 09:47:00 [Lightdash] info: Worker worker-b713d00141cfe9e847 errored job 744 (handleScheduledDelivery). NotFoundError: Scheduler not found
2023-05-02 09:47:00 [Lightdash] info: Worker worker-b713d00141cfe9e847 failed job 744 (handleScheduledDelivery). NotFoundError: Scheduler not found
2023-05-02 09:47:00 [Lightdash] debug: Failed task 744 (handleScheduledDelivery) with error Scheduler not found (120012.93ms):
  NotFoundError: Scheduler not found
      at SchedulerModel.<anonymous> (/Users/joaoviana/Desktop/gits/lightdash/packages/backend/src/models/SchedulerModel/index.ts:173:19)
      at Generator.next (<anonymous>)
      at fulfilled (/Users/joaoviana/Desktop/gits/lightdash/packages/backend/src/models/SchedulerModel/index.ts:5:58)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

### What problem does this solve?

Removes unnecessary tasks that do not make sense to keep on running.

**Comment by ZeRego** [comment]
We delete all jobs when the scheduler is deleted. In the case where the job has started, the graphile lib locks that row so it isn't deleted. Forcing a delete wouldn't solve the issue either since the code is being executed already. 
So throwing that error seems to be the correct way to handle this scenario.
