### ISSUE TITLE
Lightdash unable to start after upgrading in Kubernetes

### ISSUE THREAD

**Issue by LarsHanegraaf** [lightdash/lightdash#6404]
### Description

I have deployed Lightdash on Kubernetes using Argo CD and the Lightdash Helm chart.

### To Reproduce

1. Deploy Lightdash in Argo CD using the following values:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lightdash
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: lightdash
  project: default
  source:
    chart: lightdash
    repoURL: https://lightdash.github.io/helm-charts
    targetRevision: 0.8.5
    helm:
      releaseName: lightdash
      values: |
        secrets:
          LIGHTDASH_SECRET: <redacted>
        configMap:
          SITE_URL: "<redacted>"
        ingress:
          enabled: true
          annotations:
            cert-manager.io/issuer: "le-lightdash-http"
          hosts:
            - host: <redacted>
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - enabled: true
              secretName: tls-lightdash-ingress-http
              hosts:
                - <redacted>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```
2. Visit Lightdash via the ingress. (This works!)
3. Update the deployment by specifying a Lightdash version.
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lightdash
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: lightdash
  project: default
  source:
    chart: lightdash
    repoURL: https://lightdash.github.io/helm-charts
    targetRevision: 0.8.5
    helm:
      releaseName: lightdash
      values: |
        secrets:
          LIGHTDASH_SECRET: <redacted>
        configMap:
          SITE_URL: "<redacted>"
        image:
          tag: 0.672.0
        ingress:
          enabled: true
          annotations:
            cert-manager.io/issuer: "le-lightdash-http"
          hosts:
            - host: <redacted>
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - enabled: true
              secretName: tls-lightdash-ingress-http
              hosts:
                - <redacted>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```
4. This results in a container that is unable to start:
![image](https://github.com/lightdash/lightdash/assets/16350192/e89d77e7-7017-4c80-bc1d-17053ff3e50d)
With the following error message:
```
yarn workspace v1.22.19
yarn run v1.22.19
$ knex migrate:latest --knexfile dist/database/knexfile.js
Working directory changed to /usr/app/packages/backend/dist/database
Using environment: production
password authentication failed for user "lightdash"
error: password authentication failed for user "lightdash"
    at Parser.parseErrorMessage (/usr/app/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/usr/app/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/usr/app/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/usr/app/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)    at Socket.Readable.push (node:internal/streams/readable:228:10)    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /usr/local/bin/node
Arguments: /opt/yarn-v1.22.19/lib/cli.js migrate-production
Directory: /usr/app/packages/backend
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
```
5. Rolling back to the previous version, doesn't solve the problem. It gives the same error as in step 4. So now my Lightdash installation is unable to run. Deleting the pod / service and let Argo CD recreate it again, didn't solve the issue either.

### App Version

Initially I deployed the application without a tag. This resulted in running Lightdash 0.602.0

**Comment by LarsHanegraaf** [comment]
Currently used an external database and newer version of Lightdash
