### ISSUE TITLE
request to https://app.lightdash.cloud/api/v1/projects/e5ab1bb1-8306-46c3-ae1c-82a93c45069a/explores failed, reason: write EPIPE

### ISSUE THREAD

**Issue by stellar-ahmed** [lightdash/lightdash#6582]
### Description

`Lightdash preview` just failed.

Please find a text file with more context about my previous terminal commands here:

[more_context_from_terminal_.txt](https://github.com/lightdash/lightdash/files/12231486/more_context_from_terminal_.txt)

I am copy-pasting the output of the `Lightdash preview` command:

```
lightdash preview
⚠️ You are using Node.js version v18.15.0. Lightdash CLI is optimized for v16 so you might experience issues.
(node:38019) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
Warning: CLI (0.514.0) is running a different version than Lightdash (0.710.0) on https://app.lightdash.cloud.
         Some commands may fail, consider upgrading your CLI by doing: npm install -g @lightdash/cli@0.710.0

⠙   Setting up preview environment15:40:38  Running with dbt=1.4.1
15:40:38  Found 46 models, 25 tests, 0 snapshots, 0 analyses, 505 macros, 0 operations, 1 seed file, 32 sources, 0 exposures, 0 metrics
15:40:38  
15:40:39  Concurrency: 1 threads (target='dev')
15:40:39  
15:40:42  Done.

⠧   Setting up preview environment
- SUCCESS> bill_payments 
- SUCCESS> payment_orders 
- SUCCESS> daily_marketing_spend_summary 
- SUCCESS> membership_fees 
- SUCCESS> ads_kpi_summary 
- SUCCESS> kpi_summary 
- SUCCESS> members 
- SUCCESS> segment_web_app_sessions__stitched 
- SUCCESS> segment_web_app_sessions 
- SUCCESS> segment_web_app_user_stitching 
- SUCCESS> segment_web_app_sessions__initial 
- SUCCESS> segment_web_app_page_views__sessionized 
- SUCCESS> stg_member_credit_summary 
- SUCCESS> stg_membership_fees_summary 
- SUCCESS> stg_segment_web_app_page_views 
- SUCCESS> stg_segment_web_app_user_activated 
- SUCCESS> stg_payment_orders 
- SUCCESS> stg_member_goals 
- SUCCESS> stg_segment_calculated_traits 
- SUCCESS> stg_segment_web_app_member_registrations 
- SUCCESS> stg_member_socure_transaction_risks 
- SUCCESS> stg_member_spend_limits 
- SUCCESS> stg_member_subscriptions 
- SUCCESS> stg_payable_collection_status_cutoffs 
- SUCCESS> stg_facebook_ads_data 
- SUCCESS> stg_members 
- SUCCESS> stg_lithic_transactions 
- SUCCESS> stg_member_plaid_items 
- SUCCESS> stg_member_socure_account_intelligence_transactions 
- SUCCESS> stg_member_socure_transaction_device_risks 
- SUCCESS> stg_google_ads_data 
- SUCCESS> stg_payment_order_status_cutoffs 
- SUCCESS> stg_member_promocode_stats 
- SUCCESS> stg_all_risk_reason_codes 
- SUCCESS> stg_bill_payments_summary 
- SUCCESS> stg_member_socure_transaction_document_risks 
- SUCCESS> stg_member_socure_transaction_email_risks 
- SUCCESS> stg_member_promocodes 
- SUCCESS> stg_datespine 
- SUCCESS> stg_socure_transactions 
- SUCCESS> stg_membership_fees 
- SUCCESS> stg_payment_order_returns 
- SUCCESS> stg_bills 
- SUCCESS> stg_id_verifications 
- SUCCESS> daily_marketing_campaign_analysis 
- SUCCESS> members_risk 

Compiled 46 explores, SUCCESS=46 ERRORS=0
✖ Error creating developer preview
request to https://app.lightdash.cloud/api/v1/projects/e5ab1bb1-8306-46c3-ae1c-82a93c45069a/explores failed, reason: write EPIPE
FetchError: request to https://app.lightdash.cloud/api/v1/projects/e5ab1bb1-8306-46c3-ae1c-82a93c45069a/explores failed, reason: write EPIPE
    at ClientRequest.<anonymous> (/Users/home/.nvm/versions/node/v18.15.0/lib/node_modules/@lightdash/cli/node_modules/node-fetch/lib/index.js:1505:11)
    at ClientRequest.emit (node:events:513:28)
    at ClientRequest.emit (node:domain:489:12)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket.emit (node:domain:489:12)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'EPIPE',
  code: 'EPIPE'
}
FetchError: request to https://app.lightdash.cloud/api/v1/projects/e5ab1bb1-8306-46c3-ae1c-82a93c45069a/explores failed, reason: write EPIPE
    at ClientRequest.<anonymous> (/Users/home/.nvm/versions/node/v18.15.0/lib/node_modules/@lightdash/cli/node_modules/node-fetch/lib/index.js:1505:11)
    at ClientRequest.emit (node:events:513:28)
    at ClientRequest.emit (node:domain:489:12)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket.emit (node:domain:489:12)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Report this issue with 1-click:

  🐛 https://github.com/lightdash/lightdash/issues/new?assignees=&labels=🐛+bug&template=bug_report.md&title=request%20to%20https%3A%2F%2Fapp.lightdash.cloud%2Fapi%2Fv1%2Fprojects%2Fe5ab1bb1-8306-46c3-ae1c-82a93c45069a%2Fexplores%20failed%2C%20reason%3A%20write%20EPIPE
```

### To Reproduce

simply execute `Lightdash preview` I suppose ? after you've run `Lightdash dbt run --select <your_own_experimentally-changed-model>` 

### App Version

Version: v0.710.0

**Comment by ZeRego** [comment]
> Warning: CLI (0.514.0) is running a different version than Lightdash (0.710.0) on https://app.lightdash.cloud.
         Some commands may fail, consider upgrading your CLI by doing: npm install -g @lightdash/cli@0.710.0

@stellar-ahmed have you tried updating the CLI ? The version difference is quite big. 

https://docs.lightdash.com/guides/cli/how-to-upgrade-cli

**Comment by TuringLovesDeathMetal** [comment]
Closed assuming that this is solved by updating the CLI - will reopen if ht eproblem persists

**Comment by stellar-ahmed** [comment]
Thank you !! it seemed to be a very rare issue that was happening to me multiple times during that time haha but it has never occured !
