### ISSUE TITLE
Can't restart docker container 

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#714]
After using the install script to build the docker container, when we want to restart the container it gives an error.

```
yarn workspace v1.22.5

yarn run v1.22.5

$ knex migrate:latest --knexfile dist/database/knexfile.js

Working directory changed to /usr/app/packages/backend/dist/database

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Must specify environment variable LIGHTDASH_SECRET. Keep this value hidden!

ParseError: Must specify environment variable LIGHTDASH_SECRET. Keep this value hidden!

    at mergeWithEnvironment (/usr/app/packages/backend/dist/config/parseConfig.js:71:15)

    at Object.parseConfig (/usr/app/packages/backend/dist/config/parseConfig.js:100:12)

    at Object.<anonymous> (/usr/app/packages/backend/dist/config/lightdashConfig.js:42:41)

    at Module._compile (internal/modules/cjs/loader.js:1072:14)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)

    at Module.load (internal/modules/cjs/loader.js:937:32)

    at Function.Module._load (internal/modules/cjs/loader.js:778:12)

    at Module.require (internal/modules/cjs/loader.js:961:19)

    at require (internal/modules/cjs/helpers.js:92:18)

    at Object.<anonymous> (/usr/app/packages/backend/dist/database/knexfile.js:8:27)

error Command failed with exit code 1.

error Command failed.

Exit code: 1

Command: /usr/bin/node

Arguments: /usr/share/yarn/lib/cli.js migrate-production

Directory: /usr/app/packages/backend

Output:


info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
```

The lightdash secret env var is being set by the install script. I suspect it is necessary to restart the container but there isn't a way to do it via the docker app.

**Comment by ZeRego** [comment]
Command to restart is
```sudo PORT="8080" PGPASSWORD="password" LIGHTDASH_SECRET="not very secret" docker-compose -f docker-compose.yml start ```

**Comment by owlas** [comment]
@ZeRego should we write these into `.env` when the setup script is run?
