### ISSUE TITLE
Add error handling to catch ssh tunnel closing

### ISSUE THREAD

**Issue by magnew** [lightdash/lightdash#7444]
### Description

When using an SSH tunnel to connect to a warehouse, the Lightdash server doesn't handle errors thrown when the tunnel closes. We should add a try/catch and keep the server from crashing in the case of these unhandled exceptions. 

Here is a sample log when this crash happens:

```
level”:“error”,“message”:“Uncaught Exception thrown This socket has been ended by the other party”,“stack”:“Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (node:net:569:14)
    at Channel.ondata (node:internal/streams/readable:777:22)
    at Channel.emit (node:events:517:28)
    at Channel.emit (node:domain:552:15)
    at addChunk (node:internal/streams/readable:335:12)
    at readableAddChunk (node:internal/streams/readable:308:9)
    at Readable.push (node:internal/streams/readable:245:10)
    at CHANNEL_DATA (/usr/app/node_modules/ssh2/lib/client.js:587:23)
    at 94 (/usr/app/node_modules/ssh2/lib/protocol/handlers.misc.js:930:16)
    at Protocol.onPayload (/usr/app/node_modules/ssh2/lib/protocol/Protocol.js:2052:10)
    at AESGCMDecipherNative.decrypt (/usr/app/node_modules/ssh2/lib/protocol/crypto.js:987:26)
    at Protocol.parsePacket [as _parse] (/usr/app/node_modules/ssh2/lib/protocol/Protocol.js:2021:25)
    at Protocol.parse (/usr/app/node_modules/ssh2/lib/protocol/Protocol.js:306:16)
    at Socket.<anonymous> (/usr/app/node_modules/ssh2/lib/client.js:775:21)
    at Socket.emit
```

**Comment by rephus** [comment]
Logs on gCP https://console.cloud.google.com/logs/query;query=SEARCH%2528%22This%20socket%20has%20been%20ended%22%2529;cursorTimestamp=2023-10-12T10:49:32.933168249Z;startTime=2023-10-12T04:51:56.698Z;endTime=2023-10-12T11:51:56.698793Z?referrer=search&authuser=1&project=lightdash-cloud-beta

**Comment by rephus** [comment]
Investigation thread: https://lightdash.slack.com/archives/C02GQKJK84Q/p1697121193135549?thread_ts=1697114449.868889&cid=C02GQKJK84Q

**Comment by rephus** [comment]
It seems hard to capture the error from pg.pool.connect. (see slack thread)

We could implement a method to check if the SSH tunnel is alive right before running the query, something like `sshTunnel.exec('whoami')`

**Comment by rephus** [comment]
I got this log locally :thinking: 

![image](https://github.com/lightdash/lightdash/assets/1983672/4bc103cb-2dac-4a40-a20c-1fcea842cb2c)
