### ISSUE TITLE
request to http://localhost:3000/api/v1/user failed, reason: connect ECONNREFUSED 127.0.0.1:3000

### ISSUE THREAD

**Issue by timhiebenthal** [lightdash/lightdash#9465]
### Description

I installed the Lightdash CLI (v0.1036.5) locally and wanted to login with ` lightdash login http://localhost:3000 --token ...`.
Ended up with 

```
request to http://localhost:3000/api/v1/user failed, reason: connect ECONNREFUSED 127.0.0.1:3000
FetchError: request to http://localhost:3000/api/v1/user failed, reason: connect ECONNREFUSED 127.0.0.1:3000
    at ClientRequest.<anonymous> (/home/thiebenthal_ubuntu/.npm-global/lib/node_modules/@lightdash/cli/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at Socket.socketErrorListener (node:_http_client:495:9)
    at Socket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED'
}
FetchError: request to http://localhost:3000/api/v1/user failed, reason: connect ECONNREFUSED 127.0.0.1:3000
    at ClientRequest.<anonymous> (/home/thiebenthal_ubuntu/.npm-global/lib/node_modules/@lightdash/cli/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at Socket.socketErrorListener (node:_http_client:495:9)
    at Socket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Report this issue with 1-click:

  🐛 https://github.com/lightdash/lightdash/issues/new?assignees=&labels=🐛+bug&template=bug_report.md&title=request%20to%20http%3A%2F%2Flocalhost%3A3000%2Fapi%2Fv1%2Fuser%20failed%2C%20reason%3A%20connect%20ECONNREFUSED%20127.0.0.1%3A3000
```

### Context
Running within WSL2 (Ubuntu) on Windows 11

installing through `./scripts/install.sh`  failed because my Docker Desktop instance is somehow not detected by the install-script but manual `docker-compose up -d` worked

### App Version

0.1036.5

**Comment by filp** [comment]
Hi @timhiebenthal - based on that error it appears Lightdash isn't running, or is unable to accept connection.

Could you check your container logs, and share them here (please verify there is no sensitive information contained within any logs you share)?

You can access logs for all Lightdash containers via `docker compose logs`, from the same directory from which you ran `docker compose up -d`.

**Comment by TuringLovesDeathMetal** [comment]
closing this as not planned since htere has been no activity for more than 6 months
